### ISSUE TITLE
Assistance to cp/mv files on folder sync completion

### ISSUE THREAD

**Issue by zilexa** [jpmens/syncthing-activity#1]
Hi @jpmens I am looking for friendly advice/tips to use your script to continuously monitor a couple of folders (1 per device) and when syncing for a folder is completed, copy its contents to a backup location (local folder).

I believe your script already does nearly everything I am looking for. 

If I am right, I just have to change in line 35 the event `ItemStarted` you are watching to `FolderCompletion`.
Then instead of the `print` command on line 60, use an `rsync` command to copy files that don't exist yet or are older at the backup location. 

I am really a noob when it comes to scripting. I understand you abandoned this project or it has been fulfilling a need perfectly well all this time. Just looking for friendly advice here.

**Comment by jpmens** [comment]
> If I am right, I just have to change in line 35 the event ItemStarted you are watching to FolderCompletion

possibly. That _sounds_ right, but I've never done it.

> Then instead of the print command on line 60

That also sounds right to me.

I've not abandoned this. I use it still, exactly as it is now. :-)

**Comment by zilexa** [comment]
OK I am testing your script, as is. I created the env var for the API key and  now run it like this:
`./syncthing-activity.py docs`

On the local machine I have Syncthing syncing 2 folders `Zilexa's docs` and `Other docs`. But the terminal stays empty. 
I also tried a different one::
`./syncthing-activity.py Desktop` as I also sync a folder called `Desktop`. Again, terminal stays empty. 

I tested by creating new text files on the local machine in those folders or by copying PDF files into them. 

What am I missing here?

**Comment by jpmens** [comment]
Try invoking the program without an argument, i.e. as `./synching-activity.py`

**Comment by zilexa** [comment]
OK looks like I created the .py file with sudo. This time did it without and also ran it without sudo. Now it works. 
However when I change the event to `FolderCompletion` it doesn't work. There is no output. I'll ask on SyncThing forum for a little help.

**Comment by zilexa** [comment]
My mistake, the event name ItemStarted is used on line 35 and 73. After changing also 73 to Foldercompletion, the script does something after I copied a file into a folder. But it crashes: 

```
/syncthing-activity.py
Traceback (most recent call last):
  File "./syncthing-activity.py", line 96, in <module>
    main(url, apikey, pattern)
  File "./syncthing-activity.py", line 78, in main
    process(json.loads(r.text), pat)
  File "./syncthing-activity.py", line 42, in process
    path = os.path.join(folder_path, event["data"]["item"])
KeyError: 'item'
```
Any thoughts?

**Comment by zilexa** [comment]
I have got step 1 working with lots of trial and error! [My fork](https://github.com/zilexa/syncthing-backup/blob/master/syncthing-backup.py).
My changes: 

- I modified the script to only act on ~~FolderCompletion~~ ItemFinished.
- Get relevant parameters for ItemFinished
- [line 64](https://github.com/zilexa/syncthing-backup/blob/master/syncthing-backup.py#L64): check if ItemFinished event was a successful file operation
- Print this output to a logfile using Python logging module instead of printing on terminal:
```
2020-10-29 18:21:46,813 INFO     2020-10-29T18:13:05.879846929+01:00 ItemFinished     update      Zilexa's docs /mnt/pool/Users/Local/Zilexa/Mytestdoc (another copy).pdf
2020-10-29 18:21:56,824 DEBUG    Starting new HTTP connection (1): 192.168.88.10:8384
```
It works with `./syncthing-activity.py photos`.
This means I could use it to monitor only folders with "photos" in their label name :)

~~I still need help with [line 69](https://github.com/zilexa/syncthing-backup/blob/master/syncthing-backup.py#L69)~~:
I check if action=update, but I also need to check if error=null.
I tried `if event["data"]["action"] == "update" and event["data"]["error"] == "null":`
For some reason I cannot get this last piece to work. Perhaps null means the parameter does not exist? I need this according to the documentation to verify if it was a successful file update:  https://docs.syncthing.net/events/itemfinished.html

Sorry to ask, I googled a bit but couldn't figure it out. I got this far by hours of trial and error as I don't know Python.
BTW I use ItemFinished now instead of FolderCompletion. ItemFinished allows me to perform an action per file (backing it up) which makes more sense.

**Comment by zilexa** [comment]
Figured it out. The script works with ==None instead of =="null". But I cannot test properly since I cannot simply simulate an error. 

At least it works now so I will add my cp && mv or rsync && mv command and finish it.

**Comment by zilexa** [comment]
I do need your help, sorry. I can't figure this last part out. How can I use the declared variables in a copy command?
I am having trouble passing the vars to my `cp` command. I simply do not know how to do that. For example I tried ([line 69](https://github.com/zilexa/syncthing-backup/blob/master/syncthing-backup.py#L69)):

```
cp -u --preserve=timestamps "file_path" /mnt/pool/Collections/Pictures/Test/
mv "file_path" "folder_path"/archive
```
But that gives syntax errors. I tried without quotations "" but that didn't help. 
The variables do print successfully in my logfile (folder_path, file_path,  folder_label). 

Note I renamed your `path` to `file_path` to prevent confusion with `folder_path`. 
Can you assist here?
